language: python
addons:
  apt:
    packages:
    - zlib1g-dev
    - libncurses5-dev
python:
  - 3.4
sudo: false
install:
  - source ./install_dependencies.sh
before_script:
  - pip install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov
